version: "3.8"

services:

  # MySQL 数据库服务
  mysql:
    image: mysql:${MYSQL_IMAGE_VERSION}
    container_name: ${APP_NAME}-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - ${APP_NAME}-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Nginx Web 服务器
  nginx:
    image: nginx:${NGINX_IMAGE_VERSION}
    container_name: ${APP_NAME}-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./sites/cn.podcast.aripplesong.me/public:/var/www/cn.podcast.aripplesong.me
      - ./sites/doc.podcast.aripplesong.me/public:/var/www/doc.podcast.aripplesong.me
      - ./sites/podcast.aripplesong.me/public:/var/www/podcast.aripplesong.me
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - ${APP_NAME}-network
    depends_on:
      - php-cn-podcast
      - php-doc-podcast
      - php-podcast
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"     


  # CN Podcast PHP-FPM
  php-cn-podcast:
    image: php:${PHP_IMAGE_VERSION}
    container_name: ${APP_NAME}-php-cn-podcast
    restart: always
    environment:
      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - ./sites/cn.podcast.aripplesong.me/public:/var/www/cn.podcast.aripplesong.me
      - ./sites/cn.podcast.aripplesong.me/php.ini:/usr/local/etc/php/php.ini
    networks:
      - ${APP_NAME}-network
    depends_on:
      mysql:
        condition: service_healthy     


  # CN Podcast PHP-FPM
  php-podcast:
    image: php:${PHP_IMAGE_VERSION}
    container_name: ${APP_NAME}-php-podcast
    restart: always
    environment:
      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - ./sites/podcast.aripplesong.me/public:/var/www/podcast.aripplesong.me
      - ./sites/podcast.aripplesong.me/php.ini:/usr/local/etc/php/php.ini
    networks:
      - ${APP_NAME}-network
    depends_on:
      mysql:
        condition: service_healthy     

  # doc Podcast PHP-FPM
  php-doc-podcast:
    image: php:${PHP_IMAGE_VERSION}
    container_name: ${APP_NAME}-php-doc-podcast
    restart: always
    environment:
      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - ./sites/doc.podcast.aripplesong.me/public:/var/www/doc.podcast.aripplesong.me
      - ./sites/doc.podcast.aripplesong.me/php.ini:/usr/local/etc/php/php.ini
    networks:
      - ${APP_NAME}-network
    depends_on:
      mysql:
        condition: service_healthy

networks:
  ${APP_NAME}-network:
    driver: bridge
