services:
  # MySQL 数据库服务
  mysql:
    image: mysql:8.4.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "mysqladmin",
    #       "ping",
    #       "-h",
    #       "localhost",
    #       "-uroot",
    #       "-p${MYSQL_ROOT_PASSWORD}",
    #       "--silent",
    #     ]
    #   timeout: 20s
    #   retries: 10

  # Nginx Web 服务器
  nginx:
    image: nginx:1.28.0
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./sites:/var/www/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    networks:
      - app-network
    depends_on:
      - php-${php_version}
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  # WordPress CLI
  wpcli:
    image: wordpress:cli
    volumes:
      - ./sites:/var/www
    working_dir: /var/www/html
    networks:
      - app-network

  # main site PHP-FPM
  php-8.4.15:
    image: php:8.4.15-fpm-alpine3.21
    restart: always
    environment:
      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - ./sites:/var/www
      - ./php/8.4.15/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge
